something = input("Digite algo: ")
print(f'O tipo primitivo desse valor é: {type(something)}')
print(f'Tem espaços? {something.isspace()}')
print(f'É um número? {something.isnumeric()}')
print(f'É alfabético? {something.isalpha()}')
print(f'É alfanúmerico? {something.isalnum()}')
print(f'Está em maiúsculas? {something.isupper()}')
print(f'Está em minúscula? {something.islower()}')
print(f'Está capitalizado? {something.istitle()}')